#!/usr/bin/env python3
"""lut_to_case.py <module.v> <module_name> <in_port> <in_bits> <out_port> <out_bits>

Rewrite a small combinational module (for example a Yosys-style LUT netlist of
`assign b = 64'hK >> {...};` lines) as a bit-identical `case` table, by
evaluating every input value with iverilog.  Gowin synthesized such a LUT
netlist wrongly once it was merged with surrounding logic (docs/04, pitfall 2);
the case form synthesized correctly.  Writes <module_name>_case.v.
MIT license -- see the repository LICENSE.
"""
import os, subprocess, sys, tempfile

src, mod, inp, ib, outp, ob = sys.argv[1:7]
ib, ob = int(ib), int(ob)
if ib > 16:
    sys.exit('input too wide for an exhaustive table')
with tempfile.TemporaryDirectory() as d:
    tb = os.path.join(d, 'tb.v')
    open(tb, 'w').write(f"""module tb; reg [{ib-1}:0] i; wire [{ob-1}:0] o; integer k;
  {mod} u (.{inp}(i), .{outp}(o));
  initial begin for (k = 0; k < {1 << ib}; k = k + 1) begin i = k; #1; $display("%h %h", i, o); end $finish; end
endmodule
""")
    subprocess.run(['iverilog', '-o', os.path.join(d, 'sim'), tb, src], check=True)
    out = subprocess.run(['vvp', '-n', os.path.join(d, 'sim')], capture_output=True, text=True).stdout
rows = [l.split() for l in out.splitlines() if len(l.split()) == 2 and 'finish' not in l]
assert len(rows) == 1 << ib, f'expected {1 << ib} rows, got {len(rows)}'
body = '\n'.join(f"            {ib}'h{a}: {outp} = {ob}'h{b};" for a, b in rows)
open(f'{mod}_case.v', 'w').write(f"""// {mod} -- generated by lut_to_case.py: a {1 << ib}-entry case table,
// bit-identical to the original module (exhaustively evaluated).
module {mod}({inp}, {outp});
    input  [{ib-1}:0] {inp};
    output reg [{ob-1}:0] {outp};
    always @(*) begin
        case ({inp})
{body}
            default: {outp} = {ob}'h0;
        endcase
    end
endmodule
""")
print(f'wrote {mod}_case.v ({len(rows)} entries)')
